### PR TITLE
upgrade to Aff 4.0

### PR DESCRIPTION
**Pull request by justinwoo**
upgrades to Aff 4.0 and simplifies the FFI

### CODE REVIEW

**Comment by tonyd256** [comment]
Any update on when this can get pulled in?

**Comment by tonyd256** [comment]
@nwolverson Would you be able to release a new version with these changes in them when you have some time :)

**Comment by nwolverson** [comment]
Time, I have not.

Tagged a release...

**Comment by tonyd256** [comment]
Well thank you for doing it! I would have done it for you if that's how github permissions worked :)

**Pull request merged**
